name: QodanaCustomImageJob
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to Jetbrains Space
        uses: docker/login-action@v2
        with:
          registry: registry.jetbrains.team
          username: ${{ secrets.SPACE_USER }}
          password: ${{ secrets.SPACE_PASSWORD }}
      - run: docker pull registry.jetbrains.team/p/sa/containers/qodana-cpp:2024.2-nightly
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@2024.1.8
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: "--linter,registry.jetbrains.team/p/sa/containers/qodana-cpp:2024.2-nightly"
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ${{ runner.temp }}/qodana/results/
